# Generated by Django 5.1.4 on 2026-09-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='线路名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='状态')),
                ('start_point', models.CharField(blank=True, default='', max_length=120, verbose_name='起点')),
                ('end_point', models.CharField(blank=True, default='', max_length=120, verbose_name='终点')),
                ('difficulty', models.CharField(blank=True, choices=[('亲子', '亲子（轻松休闲）'), ('成人', '成人（标准挑战）'), ('专业', '专业（高强度越野）')], default='', max_length=16, verbose_name='难度')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='预计时长（分钟）')),
                ('equipment', models.TextField(blank=True, default='', verbose_name='装备要求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '线路',
                'verbose_name_plural': '线路',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='打卡点名称')),
                ('clue', models.TextField(blank=True, default='', verbose_name='线索')),
                ('task', models.TextField(blank=True, default='', verbose_name='任务')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='domain.route', verbose_name='所属线路')),
            ],
            options={
                'verbose_name': '打卡点',
                'verbose_name_plural': '打卡点',
                'ordering': ['order', 'id'],
            },
        ),
    ]
